#! usr/bin/bash

#bash 1

mkdir Namizje
mkdir slike 
mkdir dokumenti
cd Namizje
mkdir Aplikacije
mkdir datoteke


bash 2

for((i=4; i>=0; i--))
do
  mkdir folder"$i"
done


#bash 3

for ((i=25; i>=22; i--))
do
 useradd -m -G sudo user"$i"



done

#bash 4

do
sudo apt list --upgradable
sudo apt-get update
done


#bash 5


sudo apt install ufw
sudo apt-get install git-all
git version 
sudo apt-get install -y net-tools





#bash 6
do
sudo apt-get remove docker docker-engine docker.io containerd runc
sudo apt-get update
sudo apt-get install ca-certificates curl gnupg  lsb-release
sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gp] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null 
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin
sudo docker run hello-world
done
